package sg.edu.nus.soc.cs5231;

public class PackageWhiteList {

	public final static String [] whiteList = {
//		"com.magicwach.rdefense",
//		"com.xxx.yyy",
//		"cn.beauty.leg",
//		"com.android.root",
//		"jackpal.androidterm",
//		"net.youmi.android",
//		"com.google.ssearch",
//		"com.tutusw.phonespeedup",
//		"uk.co.lilhermit.android.core",
//		"com.adwo.adsdk",
//		"com.google.update",
//		"com.ps.llk",
//		"com.android.vending.licensing",
//		"com.flurry.android",
//		"com.masshabit.build",
//		"com.masshabit.common",
//		"com.masshabit.common.curve",
//		"com.masshabit.common.entity",
//		"com.masshabit.common.physics",
//		"com.masshabit.common.resource",
//		"com.masshabit.common.tween",
//		"com.masshabit.squibble",
//		"com.masshabit.squibble.free",
//		"com.masshabit.squibble.free.activity",
//		"com.masshabit.squibble.free.activity.a",
//		"com.masshabit.squibble.free.activity.b",
//		"com.masshabit.squibble.free.activity.c",
//		"com.masshabit.squibble.free.activity.d",
//		"com.masshabit.squibble.free.activity.e",
//		"de.mobinauten.smsspy"
//		"jp.naver.line.android",//TEST
		"android",
		"com.android.backupconfirm",
		"com.android.bluetooth",
		"com.android.calculator2",
		"com.android.certinstaller",
		"com.android.contacts",
		"com.android.defcontainer",
		"com.android.facelock",
		"com.android.htmlviewer",
		"com.android.inputdevices",
		"com.android.keychain",
		"com.android.launcher",
		"com.android.mms",
		"com.android.musicfx",
		"com.android.musicvis",
		"com.android.nfc",
		"com.android.noisefield",
		"com.android.packageinstaller",
		"com.android.phasebeam",
		"com.android.phone",
		"com.android.providers.applications",
		"com.android.providers.calendar",
		"com.android.providers.contacts",
		"com.android.providers.downloads",
		"com.android.providers.downloads.ui",
		"com.android.providers.drm",
		"com.android.providers.media",
		"com.android.providers.settings",
		"com.android.providers.telephony",
		"com.android.providers.userdictionary",
		"com.android.settings",
		"com.android.sharedstoragebackup",
		"com.android.soundrecorder",
		"com.android.stk",
		"com.android.systemui",
		"com.android.vending",
		"com.android.vpndialogs",
		"com.android.wallpaper",
		"com.android.wallpaper.holospiral",
		"com.android.wallpaper.livepicker",
		"com.google.android.apps.books",
		"com.google.android.apps.currents",
		"com.google.android.apps.genie.geniewidget",
		"com.google.android.apps.magazines",
		"com.google.android.apps.maps",
		"com.google.android.apps.plus",
		"com.google.android.apps.uploader",
		"com.google.android.backup",
		"com.google.android.browser",
		"com.google.android.calendar",
		"com.google.android.deskclock",
		"com.google.android.ears",
		"com.google.android.email",
		"com.google.android.exchange",
		"com.google.android.feedback",
		"com.google.android.gallery3d",
		"com.google.android.gm",
		"com.google.android.gms",
		"com.google.android.googlequicksearchbox",
		"com.google.android.gsf",
		"com.google.android.gsf.login",
		"com.google.android.inputmethod.latin",
		"com.google.android.inputmethod.latin.dictionarypack",
		"com.google.android.location",
		"com.google.android.marvin.talkback",
		"com.google.android.music",
		"com.google.android.onetimeinitializer",
		"com.google.android.partnersetup",
		"com.google.android.setupwizard",
		"com.google.android.street",
		"com.google.android.syncadapters.bookmarks",
		"com.google.android.syncadapters.contacts",
		"com.google.android.tag",
		"com.google.android.talk",
		"com.google.android.tts",
		"com.google.android.videoeditor",
		"com.google.android.videos",
		"com.google.android.voicesearch",
		"com.google.android.youtube",
		"com.google.earth",
		"com.tf.thinkdroid.sg",
		"de.robv.android.xposed.installer",
		"eu.chainfire.supersu",
		"sg.edu.nus.soc.cs5231"

	};
	
	public static boolean IsInWhiteList(String target)
	{
//		return true;
//		Logger
		for(String s : whiteList)
		{
			if(s.equals(target))
			{
				return false;
			}
		}
		return true;
	}
	
}
